name: lingyue_mobile
description: Ling Yue MOBA - Mobile Edition (Immortal Origin)
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  flick_video_player: ^0.5.0
  google_fonts: ^6.1.0
  flame: ^1.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
